version: '3.8'

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - ./project:/home/coder/project
      - ./config:/home/coder/.local/share/code-server
    user: "0:0"
    command:
      - code-server
      - --bind-addr
      - 0.0.0.0:8080
      - --auth
      - password
      - --disable-telemetry
